################################################################################
# Terraform Remote State Backend — Bootstrap Module
#
# PURPOSE: Creates the S3 bucket and DynamoDB table that ALL other modules
# in this repo use as their Terraform backend. Apply this module first with
# a local backend, then migrate to S3 (see state-backend/README.md).
#
# APPLY ORDER:
#   Phase 1: terraform init && terraform apply   (local state)
#   Phase 2: Add backend "s3" block → terraform init -migrate-state
################################################################################

terraform {
  required_version = ">= 1.5.0, < 2.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.30"
    }
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = merge(var.tags, {
      ManagedBy = "terraform"
      Module    = "state-backend"
      Repo      = "cloud-architect-portfolio"
    })
  }
}

################################################################################
# Data — current account and partition (used in bucket policies)
################################################################################

data "aws_caller_identity" "current" {}
data "aws_partition" "current" {}

locals {
  account_id = data.aws_caller_identity.current.account_id
  partition  = data.aws_partition.current.partition
}

################################################################################
# KMS Key for State Bucket Encryption
#
# WHY a CMK instead of aws:s3?
# - You control the key policy — you can restrict which IAM principals can
#   decrypt state (i.e., which CI roles can read/write Terraform state)
# - CloudTrail logs every KMS API call — you get an audit trail of every
#   state file read and write at the cryptographic level
# - Required for MFA Delete + SSE-KMS combination (aws:s3 cannot be used
#   with MFA Delete on versioned buckets in all configurations)
################################################################################

resource "aws_kms_key" "state" {
  description             = "KMS CMK for Terraform state bucket encryption — ${var.bucket_name}"
  deletion_window_in_days = 30 # WHY 30: AWS minimum is 7 days. 30 gives time to recover
  # from accidental deletion before the key is gone forever.
  enable_key_rotation = true # WHY: AWS rotates the backing key material annually.
  # Same key ID — no Terraform changes needed.
  is_enabled = true

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        # Allow root account full control — required or the key becomes unmanageable
        Sid    = "AllowRootAccountFullControl"
        Effect = "Allow"
        Principal = {
          AWS = "arn:${local.partition}:iam::${local.account_id}:root"
        }
        Action   = "kms:*"
        Resource = "*"
      },
      {
        # Allow S3 service to use the key for SSE operations
        Sid    = "AllowS3ServiceUse"
        Effect = "Allow"
        Principal = {
          Service = "s3.amazonaws.com"
        }
        Action = [
          "kms:GenerateDataKey",
          "kms:Decrypt"
        ]
        Resource = "*"
      }
    ]
  })
}

resource "aws_kms_alias" "state" {
  name          = "alias/${var.bucket_name}"
  target_key_id = aws_kms_key.state.key_id
}

################################################################################
# Access Log Bucket
#
# WHY a separate log bucket?
# - The state bucket cannot log to itself (S3 access logging requires a
#   different target bucket to avoid recursive log generation)
# - Separating logs from state ensures log integrity — access to state
#   does not grant access to delete the logs of that access
################################################################################

resource "aws_s3_bucket" "logs" {
  bucket = var.log_bucket_name

  # WHY force_destroy = false (default):
  # Prevent accidental destruction of the audit log — logs may be required
  # for compliance (SOC 2, PCI DSS) and cannot be recovered once deleted.
  force_destroy = false
}

resource "aws_s3_bucket_versioning" "logs" {
  bucket = aws_s3_bucket.logs.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "logs" {
  bucket = aws_s3_bucket.logs.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
      # WHY AES256 for log bucket (not KMS)?
      # Access logs are generated by the S3 service itself. Using SSE-KMS
      # for the log bucket creates a chicken-and-egg KMS dependency during
      # S3's internal log delivery. AES256 (SSE-S3) is simpler and sufficient
      # for access logs which are not secret themselves.
    }
  }
}

resource "aws_s3_bucket_public_access_block" "logs" {
  bucket = aws_s3_bucket.logs.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_lifecycle_configuration" "logs" {
  bucket = aws_s3_bucket.logs.id

  rule {
    id     = "expire-old-logs"
    status = "Enabled"

    filter {}

    expiration {
      days = 365 # WHY 365: Retain one year of access logs for audit/compliance.
    }

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}

################################################################################
# State Bucket
################################################################################

resource "aws_s3_bucket" "state" {
  bucket = var.bucket_name

  # WHY force_destroy = false:
  # The state bucket contains the source of truth for all infrastructure.
  # A terraform destroy should never be able to delete this bucket by accident.
  # Removing this safeguard requires a deliberate code change + peer review.
  force_destroy = false

  lifecycle {
    prevent_destroy = true
    # WHY prevent_destroy: Double protection. Even if force_destroy is changed,
    # prevent_destroy stops `terraform destroy` from running successfully.
    # Removing prevent_destroy requires changing this code and re-applying —
    # a deliberate 2-step action that cannot happen by accident.
  }
}

# Versioning — required for state recovery
resource "aws_s3_bucket_versioning" "state" {
  bucket = aws_s3_bucket.state.id

  versioning_configuration {
    status = "Enabled"
    # WHY Enabled (not Suspended):
    # Every terraform apply overwrites the state file. Without versioning,
    # there is no way to recover from a corrupted or accidentally overwritten
    # state file. Versioning gives you a point-in-time history to roll back to.

    # NOTE: mfa_delete requires a hardware MFA device and must be enabled via
    # the AWS CLI with --mfa parameter — Terraform cannot enable it without
    # an MFA token. Enable manually with:
    #   aws s3api put-bucket-versioning \
    #     --bucket <bucket-name> \
    #     --versioning-configuration Status=Enabled,MFADelete=Enabled \
    #     --mfa "arn:aws:iam::ACCOUNT:mfa/DEVICE TOKEN"
    # mfa_delete = "Enabled"
  }
}

# Encryption — SSE-KMS with CMK
resource "aws_s3_bucket_server_side_encryption_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.state.arn
      # WHY KMS CMK (not SSE-S3 / AES256)?
      # State files contain database passwords, private key material, and
      # resource metadata. A CMK lets you:
      # (a) Restrict who can decrypt via key policy (not just bucket policy)
      # (b) Audit every decrypt operation in CloudTrail
      # (c) Rotate the encryption key on a schedule
    }

    bucket_key_enabled = true
    # WHY bucket_key_enabled = true:
    # Without bucket keys, every S3 object PUT/GET makes a KMS API call.
    # Bucket keys create a short-lived session key that reduces KMS API calls
    # by ~99%, cutting both latency and KMS costs significantly.
  }
}

# Block all public access — no exceptions
resource "aws_s3_bucket_public_access_block" "state" {
  bucket = aws_s3_bucket.state.id

  block_public_acls       = true # Ignore ACLs that grant public access
  block_public_policy     = true # Reject bucket policies that grant public access
  ignore_public_acls      = true # Ignore any existing public ACLs
  restrict_public_buckets = true # Deny requests from outside the account that are anonymous

  # WHY all four = true?
  # ACLs and bucket policies are separate access control mechanisms.
  # Setting only one leaves a gap. All four must be true to be certain.
  # AWS Foundational Security Best Practices requires all four.
}

# Access logging — who read/wrote state and when
resource "aws_s3_bucket_logging" "state" {
  bucket = aws_s3_bucket.state.id

  target_bucket = aws_s3_bucket.logs.id
  target_prefix = "s3-access-logs/${var.bucket_name}/"
  # WHY logging?
  # State access is a security event. If credentials are compromised,
  # access logs tell you: what was accessed, from which IP, at what time.
  # Required for SOC 2 CC6.8 (logical access to infrastructure controls).
}

# Lifecycle — retain 90 days of noncurrent versions, then expire
resource "aws_s3_bucket_lifecycle_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  # This depends on versioning being enabled
  depends_on = [aws_s3_bucket_versioning.state]

  rule {
    id     = "state-noncurrent-version-retention"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = var.noncurrent_version_days
      # WHY 90 days?
      # Gives the team a 3-month window to detect and recover from state
      # corruption or accidental overwrites. Beyond 90 days, old versions
      # provide no practical recovery value but accumulate storage cost.
    }

    noncurrent_version_transition {
      noncurrent_days = 30
      storage_class   = "STANDARD_IA"
      # WHY transition to IA after 30 days?
      # Noncurrent state versions are rarely accessed. IA storage reduces
      # cost ~58% vs STANDARD while remaining durable (99.999999999%).
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
      # WHY: Incomplete multipart uploads accumulate as orphaned storage.
      # Terraform does not use multipart uploads for state, but the rule
      # is defensive hygiene that costs nothing.
    }
  }
}

# Bucket policy — deny non-TLS access and enforce encryption
resource "aws_s3_bucket_policy" "state" {
  bucket = aws_s3_bucket.state.id

  # Depends on public access block — if policy is applied before the block,
  # a window exists where the bucket could accept the policy before it's locked down
  depends_on = [aws_s3_bucket_public_access_block.state]

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        # WHY DenyHTTP?
        # S3 APIs accept HTTP by default. Without this denial, someone could
        # read state files over an unencrypted connection, exposing credentials
        # in plaintext to network observers. This is required by CIS AWS
        # Foundations Benchmark v1.4 control 2.1.2.
        Sid    = "DenyNonTLSRequests"
        Effect = "Deny"
        Principal = {
          AWS = "*"
        }
        Action = "s3:*"
        Resource = [
          aws_s3_bucket.state.arn,
          "${aws_s3_bucket.state.arn}/*"
        ]
        Condition = {
          Bool = {
            "aws:SecureTransport" = "false"
          }
        }
      },
      {
        # WHY DenyUnencryptedObjectUploads?
        # Belt-and-suspenders: even if the SSE-KMS bucket default is set,
        # an API call with --no-server-side-encryption would bypass it.
        # This policy statement rejects any PUT that doesn't specify encryption.
        Sid    = "DenyUnencryptedObjectUploads"
        Effect = "Deny"
        Principal = {
          AWS = "*"
        }
        Action   = "s3:PutObject"
        Resource = "${aws_s3_bucket.state.arn}/*"
        Condition = {
          StringNotEquals = {
            "s3:x-amz-server-side-encryption" = "aws:kms"
          }
        }
      },
      {
        # WHY DenyWrongKMSKey?
        # Ensures state files are always encrypted with THIS specific CMK,
        # not any other KMS key the caller might have access to.
        Sid    = "DenyWrongKMSKey"
        Effect = "Deny"
        Principal = {
          AWS = "*"
        }
        Action   = "s3:PutObject"
        Resource = "${aws_s3_bucket.state.arn}/*"
        Condition = {
          StringNotEquals = {
            "s3:x-amz-server-side-encryption-aws-kms-key-id" = aws_kms_key.state.arn
          }
        }
      }
    ]
  })
}

################################################################################
# DynamoDB Lock Table
#
# WHY DynamoDB for locking?
# S3 does not support conditional writes or atomic test-and-set. DynamoDB
# does — PutItem with a ConditionExpression that fails if LockID already exists.
# This is how Terraform prevents two concurrent applies from corrupting state.
################################################################################

resource "aws_dynamodb_table" "state_lock" {
  name         = var.dynamodb_table_name
  billing_mode = "PAY_PER_REQUEST"
  # WHY PAY_PER_REQUEST?
  # Lock table usage is spiky — several writes during a deployment window,
  # then nothing for hours. On-demand pricing fits this pattern perfectly.
  # Provisioned throughput would require capacity planning for a table that
  # might receive one write per hour on average.

  hash_key = "LockID"
  # WHY LockID as the hash key?
  # This is the key Terraform writes. The value is:
  # "<bucket>/<key>.tfstate-md5" — unique per state file.

  attribute {
    name = "LockID"
    type = "S" # String type
  }

  point_in_time_recovery {
    enabled = true
    # WHY PITR?
    # If the lock table is corrupted (e.g., stale locks from a crashed pipeline
    # accumulate), PITR lets you restore to a specific second in the last 35 days.
    # The table is small and PITR cost is minimal (~$0.20/GB/month).
  }

  deletion_protection_enabled = true
  # WHY deletion_protection?
  # If this table is deleted, all concurrent Terraform runs become uncoordinated.
  # Two applies could corrupt the state file with no locking in place.

  server_side_encryption {
    enabled     = true
    kms_key_arn = aws_kms_key.state.arn
    # WHY KMS for DynamoDB?
    # The lock table contains state file paths and lock metadata.
    # Using the same CMK as the S3 bucket keeps the encryption boundary consistent.
  }

  tags = {
    Name = var.dynamodb_table_name
  }
}

################################################################################
# Outputs
################################################################################

################################################################################
# Variables
################################################################################
