apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web
  labels:
    app: sample-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-web
  template:
    metadata:
      labels:
        app: sample-web
    spec:
      containers:
        - name: web
          image: nginx:stable
          ports:
            - containerPort: 80
